'use strict';
(()=>{const $=id=>document.getElementById(id),KEY='aventura-admin-quizzes-v1',TK='aventura-teachers-demo-v1';let quizzes=[],teachers=['Maestro 1','Maestro 2','Maestro 3'];try{const q=JSON.parse(localStorage.getItem(KEY));if(Array.isArray(q))quizzes=q.filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string'&&['individual','grupal'].includes(x.mode));const t=JSON.parse(localStorage.getItem(TK));if(Array.isArray(t)&&t.length===3&&t.every(x=>typeof x==='string'))teachers=t;}catch(_){}
function store(key,data){try{localStorage.setItem(key,JSON.stringify(data));return true;}catch(_){$('admin-status').textContent='No se pudo guardar en este navegador.';return false;}}
teachers.forEach((name,i)=>{const label=document.createElement('label');label.textContent='Maestro '+(i+1);const input=document.createElement('input');input.required=true;input.maxLength=50;input.value=name;label.append(input);$('teacher-fields').append(label);});
function owners(){const selected=$('quiz-owner').value;$('quiz-owner').replaceChildren();teachers.forEach((name,i)=>{const o=document.createElement('option');o.value=i;o.textContent=name;$('quiz-owner').append(o);});$('quiz-owner').value=selected||'0';}
$('teachers-form').addEventListener('submit',e=>{e.preventDefault();const next=[...$('teacher-fields').querySelectorAll('input')].map(x=>x.value.trim());if(next.some(x=>!x)||new Set(next.map(x=>x.toLowerCase())).size!==3){$('admin-status').textContent='Escribe tres nombres diferentes.';return;}if(store(TK,next)){teachers=next;owners();render();$('admin-status').textContent='Nombres guardados en este dispositivo.';}});
function times(){const values=$('quiz-mode').value==='individual'?[15,12,8]:[40,60,25];$('quiz-seconds').replaceChildren();values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v+' segundos';$('quiz-seconds').append(o);});}
$('quiz-mode').addEventListener('change',times);
function reset(){ $('quiz-editor').reset();$('edit-id').value='';$('editor-heading').textContent='Crear un quiz';$('cancel-edit').hidden=true;times();}
function render(){$('quiz-list').replaceChildren();$('quiz-total').textContent=quizzes.length+' quizzes · '+quizzes.filter(q=>q.active).length+' activos';if(!quizzes.length){const p=document.createElement('p');p.className='empty';p.textContent='Tu primer quiz comienza en el formulario.';$('quiz-list').append(p);}quizzes.forEach(q=>{const card=document.createElement('article');card.className='quiz-config';const badge=document.createElement('span');badge.className='pill';badge.textContent=q.active?'Activo · local':'Borrador / desactivado';const title=document.createElement('h3');title.textContent=q.title;const meta=document.createElement('p');meta.textContent=(teachers[q.owner]||'Maestro')+' · '+q.mode+' · '+q.seconds+' s · 20 preguntas';const actions=document.createElement('div');actions.className='config-actions';const edit=document.createElement('button');edit.textContent='Editar';edit.addEventListener('click',()=>{$('edit-id').value=q.id;$('quiz-title').value=q.title;$('quiz-owner').value=q.owner;$('quiz-mode').value=q.mode;times();$('quiz-seconds').value=q.seconds;$('quiz-active').checked=q.active;$('editor-heading').textContent='Editar quiz';$('cancel-edit').hidden=false;$('quiz-title').focus();});const toggle=document.createElement('button');toggle.textContent=q.active?'Desactivar':'Activar';toggle.addEventListener('click',()=>{const next=quizzes.map(x=>x.id===q.id?{...x,active:!x.active}:x);if(store(KEY,next)){quizzes=next;render();$('admin-status').textContent='Estado actualizado. Solo afecta nuevos inicios en este navegador.';}});actions.append(edit,toggle);if(q.active){const link=document.createElement('a');link.href='quiz-jugar.html?modo='+q.mode+'&quiz='+encodeURIComponent(q.id);link.textContent='Abrir quiz →';actions.append(link);}card.append(badge,title,meta,actions);$('quiz-list').append(card);});}
$('quiz-editor').addEventListener('submit',e=>{e.preventDefault();const title=$('quiz-title').value.trim();if(!title){$('quiz-title').focus();return;}const id=$('edit-id').value||('quiz-'+Date.now()+'-'+Math.random().toString(36).slice(2,8));const q={id,title,owner:Number($('quiz-owner').value),mode:$('quiz-mode').value,seconds:Number($('quiz-seconds').value),active:$('quiz-active').checked,questionCount:20,difficulty:'avanzada'};const next=quizzes.some(x=>x.id===id)?quizzes.map(x=>x.id===id?q:x):[...quizzes,q];if(store(KEY,next)){quizzes=next;reset();render();$('admin-status').textContent='Quiz guardado en este dispositivo.';}});$('cancel-edit').addEventListener('click',reset);owners();times();render();})();