'use strict';
(()=>{const $=id=>document.getElementById(id),C=window.DetectiveCore,BANK=window.DETECTIVE_CASES,KEY='aventura-detectives-v1',SHARED='la-gran-aventura-v1';let state=null,draft=['Exploradores','Valientes','Mensajeros','Guardianes','Soñadores'];const defaults=[...draft,'Pioneros','Viajeros','Sembradores'];
function load(k){try{return JSON.parse(localStorage.getItem(k));}catch(_){return null;}}function store(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(_){$('storage-status').textContent='No se pudo guardar. Evita cerrar la página durante la partida.';}}function save(){store(KEY,state);}function el(tag,text){const n=document.createElement(tag);n.textContent=text;return n;}
function valid(s){return s?.version===1&&Array.isArray(s.teams)&&s.teams.length>=2&&s.teams.length<=8&&s.teams.every(t=>typeof t==='string')&&Array.isArray(s.deck)&&s.deck.length>=s.teams.length&&s.deck.every(c=>BANK.some(b=>b.id===c.id))&&Number.isInteger(s.turn)&&s.turn>=0&&s.turn<s.deck.length&&Array.isArray(s.marks)&&s.marks.length===3&&s.marks.every(m=>typeof m==='boolean')&&Array.isArray(s.scores)&&s.scores.length===s.teams.length&&Array.isArray(s.history)&&['ready','playing','waiting','paused','review','ended','finished'].includes(s.phase);}
const shared=load(SHARED);if(shared?.teams?.length>=2&&shared.teams.length<=8&&shared.teams.every(t=>typeof t.name==='string'))draft=shared.teams.map(t=>t.name);$('count').value=draft.length;
function read(){[...$('teams').querySelectorAll('input')].forEach((n,i)=>draft[i]=n.value.trim());}function fields(){$('teams').replaceChildren();for(let i=0;i<Number($('count').value);i++){const label=el('label','Equipo '+(i+1)),inp=document.createElement('input');inp.required=true;inp.maxLength=50;inp.value=draft[i]??defaults[i];label.append(inp);$('teams').append(label);}}$('count').addEventListener('change',()=>{read();fields();});fields();
function setup(){$('setup').hidden=false;$('play').hidden=true;$('results').hidden=true;$('scores-section').hidden=true;$('resume-box').hidden=!valid(load(KEY));$('resume').textContent=load(KEY)?.phase==='finished'?'Ver resultados guardados':'Continuar partida';}
function scoreLabel(){$('award').textContent='Guardar '+state.marks.filter(Boolean).length*10+' puntos →';}
function render(){const c=C.current(state),finished=state.phase==='finished';$('setup').hidden=true;$('play').hidden=finished;$('results').hidden=!finished;$('scores-section').hidden=false;$('ready').hidden=state.phase!=='ready';$('case-board').hidden=!['playing','waiting','review'].includes(state.phase);$('paused').hidden=state.phase!=='paused';$('review').hidden=state.phase!=='review';$('end').hidden=state.phase!=='ended';$('round').textContent=`RONDA ${C.round(state)} · EQUIPO ${C.team(state)+1} DE ${state.teams.length}`;$('team').textContent=state.teams[C.team(state)];$('last').textContent=state.lastRound===C.round(state)?'⚑ Cerramos esta ronda ✓':'⚑ Última ronda';$('last').setAttribute('aria-pressed',String(state.lastRound===C.round(state)));$('last-info').hidden=state.lastRound===null;$('last-info').textContent='Los equipos pendientes completarán esta ronda antes de terminar.';$('topic').textContent=c.topic;$('case-title').textContent=c.title;$('story').textContent=[c.mistakes[0].wrong,c.fact,c.mistakes[1].wrong,c.mistakes[2].wrong].join(' ');$('pause').disabled=state.phase!=='playing';$('reveal').disabled=!['playing','waiting'].includes(state.phase);$('feedback').textContent=state.phase==='waiting'?'¡Tiempo! Expliquen lo que encontraron antes de revelar la solución.':'';
$('corrections').replaceChildren();if(state.phase==='review'){$('reference').textContent='Para comprobar: '+c.reference;c.mistakes.forEach((m,i)=>{const card=el('article','');card.className='correction';const wrong=el('p','El relato decía: '+m.wrong);wrong.className='wrong';const right=el('p','Corrección: '+m.correct);right.className='right';const label=el('label',''),check=document.createElement('input');check.type='checkbox';check.checked=state.marks[i];check.addEventListener('change',()=>{C.mark(state,i,check.checked);save();scoreLabel();});label.append(check,el('span','El equipo identificó y corrigió este error · +10'));card.append(el('h3','Hallazgo '+(i+1)),wrong,right,label);$('corrections').append(card);});scoreLabel();}
if(state.phase==='ended'){$('turn-summary').textContent=state.history.at(-1).points+' puntos para '+state.teams[C.team(state)]+'.';$('next').textContent=state.turn+1===state.deck.length||((state.turn+1)%state.teams.length===0&&state.lastRound===C.round(state))?'Ver resultados →':'Preparar siguiente equipo →';}
$('scores').replaceChildren();state.teams.forEach((name,i)=>{const card=el('div','');card.append(el('strong',name),el('p',`${state.scores[i]} puntos · ${state.history.filter(h=>h.team===i).length} casos`));$('scores').append(card);});$('history').replaceChildren();state.history.slice().reverse().forEach(h=>{const entry=BANK.find(b=>b.id===h.caseId);$('history').append(el('li',`${state.teams[h.team]} · ${entry.title} · ${h.points} puntos · ${entry.reference}`));});if(finished){const ranked=state.teams.map((name,i)=>({name,score:state.scores[i]})).sort((a,b)=>b.score-a.score);$('result-summary').textContent=`Cada equipo investigó ${state.history.length/state.teams.length} casos. Primer lugar: ${ranked.filter(r=>r.score===ranked[0].score).map(r=>r.name).join(', ')}.`;$('podium').replaceChildren();ranked.forEach(r=>{const pos=ranked.findIndex(x=>x.score===r.score)+1,card=el('div','');card.append(el('strong',(pos<=3?['🥇','🥈','🥉'][pos-1]:pos+'.')+' '+r.name),el('p',r.score+' puntos'));$('podium').append(card);});}}
function tick(){if(!state||$('play').hidden)return;const now=Date.now();if(C.expire(state,now)){save();render();window.dispatchEvent(new CustomEvent('detective-result',{detail:'timeout'}));}const remaining=state.phase==='playing'?Math.max(0,state.deadline-now):state.phase==='paused'?state.remaining:state.phase==='ready'?90000:0;$('timer').textContent=Math.ceil(remaining/1000)+' s';$('time-bar').value=remaining/1000;}
$('setup-form').addEventListener('submit',e=>{e.preventDefault();read();const teams=draft.slice(0,Number($('count').value));if(teams.some(n=>!n)||new Set(teams.map(n=>n.toLowerCase())).size!==teams.length){$('error').textContent='Escribe un nombre diferente para cada equipo.';return;}const previous=load(KEY);if(valid(previous)&&previous.phase!=='finished'&&!confirm('¿Reemplazar la partida guardada?'))return;state=C.create(teams,BANK);store(SHARED,{...(load(SHARED)||{}),teams:teams.map(name=>({name,members:[]}))});save();render();tick();});$('start').addEventListener('click',()=>{if(C.begin(state,Date.now())){save();render();tick();}});$('reveal').addEventListener('click',()=>{if(C.reveal(state)){save();render();tick();$('review').scrollIntoView({block:'start'});}});$('award').addEventListener('click',()=>{if(C.award(state)){save();render();window.dispatchEvent(new CustomEvent('detective-result',{detail:'scored'}));}});$('pause').addEventListener('click',()=>{C.pause(state,Date.now());save();render();tick();});$('unpause').addEventListener('click',()=>{if(C.resume(state,Date.now())){save();render();tick();}});$('last').addEventListener('click',()=>{C.markLast(state);save();render();tick();});$('next').addEventListener('click',()=>{if(C.next(state)){save();render();tick();$('team').scrollIntoView({block:'start'});}});$('leave').addEventListener('click',()=>{C.pause(state,Date.now());save();setup();});$('resume').addEventListener('click',()=>{const saved=load(KEY);if(valid(saved)){state=saved;render();tick();}});$('new-game').addEventListener('click',setup);setInterval(tick,100);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});window.addEventListener('pageshow',tick);setup();
})();
