'use strict';
(()=>{const $=id=>document.getElementById(id),KEY='aventura-esgrima-v1',SHARED='la-gran-aventura-v1';const references=[];window.ESGRIMA_BOOKS.forEach(book=>book.chapters.forEach((count,c)=>{for(let v=1;v<=count;v++)references.push(book.name+' '+(c+1)+':'+v);}));
const defaults=['Exploradores','Valientes','Mensajeros','Guardianes','Soñadores','Pioneros','Viajeros','Sembradores'];let draft=defaults.slice(0,5),state=null,previous=null;
function load(key){try{return JSON.parse(localStorage.getItem(key));}catch(_){return null;}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch(_){$('storage-status').textContent='No se pudo guardar. Puedes seguir jugando, pero evita cerrar esta página.';return false;}}
function isValid(s){return s&&s.version===1&&Array.isArray(s.teams)&&s.teams.length>=2&&s.teams.length<=8&&s.teams.every(t=>typeof t==='string')&&Array.isArray(s.rounds)&&typeof s.current==='string'&&references.includes(s.current)&&['open','resolved','done'].includes(s.phase);}
const shared=load(SHARED);if(shared&&Array.isArray(shared.teams)&&shared.teams.length>=2&&shared.teams.length<=8&&shared.teams.every(t=>typeof t.name==='string'))draft=shared.teams.map(t=>t.name);$('count').value=draft.length;
function readNames(){[...$('team-inputs').querySelectorAll('input')].forEach((input,i)=>draft[i]=input.value.trim());}
function fields(){const n=Number($('count').value);$('team-inputs').replaceChildren();for(let i=0;i<n;i++){const label=document.createElement('label');label.textContent='Equipo '+(i+1);const input=document.createElement('input');input.id='group-'+i;label.htmlFor=input.id;input.required=true;input.maxLength=50;input.value=draft[i]??defaults[i];label.append(input);$('team-inputs').append(label);}}
$('count').addEventListener('change',()=>{readNames();fields();});fields();const saved=load(KEY);$('resume-box').hidden=!isValid(saved);if(saved?.phase==='done')$('resume').textContent='Ver resultados guardados';
function choose(used){const set=new Set(used),available=references.filter(ref=>!set.has(ref));return available.length?available[Math.floor(Math.random()*available.length)]:null;}
function points(){return state.teams.map((_,i)=>state.rounds.filter(r=>r.winner===i&&!r.annulled).length*100);}
function snapshot(){previous=JSON.parse(JSON.stringify(state));}
function persist(){save(KEY,state);}
function begin(teams){state={version:1,teams,rounds:[],current:choose([]),phase:'open',last:false};previous=null;persist();render();}
$('team-form').addEventListener('submit',e=>{e.preventDefault();readNames();const teams=draft.slice(0,Number($('count').value));if(teams.some(t=>!t)||new Set(teams.map(t=>t.toLocaleLowerCase('es'))).size!==teams.length){$('error').textContent='Escribe nombres diferentes para todos los equipos.';return;}if(isValid(load(KEY))&&load(KEY).phase!=='done'&&!confirm('¿Reemplazar la partida guardada por una nueva?'))return;save(SHARED,{teams:teams.map(name=>({name,members:[]})),rounds:5,games:{}});begin(teams);});
function resolve(winner,annulled,reason=''){if(state.phase!=='open')return;snapshot();state.rounds.push({reference:state.current,winner,annulled,reason});state.phase=state.last?'done':'resolved';persist();render();window.dispatchEvent(new CustomEvent('sword-result',{detail:annulled?'annulled':'winner'}));}
function render(){const done=state.phase==='done',open=state.phase==='open';$('setup').hidden=true;$('play').hidden=done;$('results').hidden=!done;$('score-section').hidden=false;$('round-number').textContent='TEXTO '+(state.rounds.length+(open?1:0));$('reference').textContent=state.current;$('last-note').hidden=!state.last;$('last').setAttribute('aria-pressed',String(state.last));$('last').textContent=state.last?'⚑ Este es el último ✓':'⚑ Último versículo';$('last').disabled=!open;$('annul').disabled=!open;$('next').disabled=open;$('undo').disabled=!previous;$('result-undo').disabled=!previous;$('winner-buttons').replaceChildren();const totals=points();state.teams.forEach((name,i)=>{const b=document.createElement('button');b.className='winner-button';b.textContent=name;b.disabled=!open;b.addEventListener('click',()=>resolve(i,false));$('winner-buttons').append(b);});const recent=state.rounds[state.rounds.length-1];$('round-status').textContent=open?'Todos buscan a la vez. Tú confirmas quién encontró y leyó correctamente.':recent.annulled?'Texto anulado. No se sumaron puntos.':state.teams[recent.winner]+' ganó este texto. +100 puntos.';$('scores').replaceChildren();state.teams.forEach((name,i)=>{const item=document.createElement('div');const label=document.createElement('strong');label.textContent=name;const value=document.createElement('span');value.textContent=totals[i]+' puntos';item.append(label,value);$('scores').append(item);});$('history').replaceChildren();state.rounds.slice().reverse().forEach(r=>{const li=document.createElement('li');li.textContent=r.reference+' — '+(r.annulled?'Anulado: '+r.reason:state.teams[r.winner]+' · +100 puntos');$('history').append(li);});if(done){const ranking=state.teams.map((name,i)=>({name,score:totals[i]})).sort((a,b)=>b.score-a.score),winners=ranking.filter(t=>t.score===ranking[0].score);$('result-title').textContent=(winners.length>1?'Primer lugar compartido: ':'Equipo ganador: ')+winners.map(t=>t.name).join(', ')+'. '+state.rounds.length+' referencias jugadas.';$('podium').replaceChildren();ranking.forEach(t=>{const pos=ranking.findIndex(x=>x.score===t.score)+1;const card=document.createElement('div');const title=document.createElement('strong');title.textContent=(pos<=3?['🥇','🥈','🥉'][pos-1]:pos+'.')+' '+t.name;const score=document.createElement('p');score.textContent=t.score+' puntos';card.append(title,score);$('podium').append(card);});}}
$('next').addEventListener('click',()=>{if(state.phase!=='resolved')return;const ref=choose(state.rounds.map(r=>r.reference));if(!ref){state.phase='done';persist();render();return;}snapshot();state.current=ref;state.last=false;state.phase='open';persist();render();$('reference').focus();});
$('last').addEventListener('click',()=>{if(state.phase!=='open')return;state.last=!state.last;persist();render();});
$('annul').addEventListener('click',()=>{if(state.phase!=='open')return;const reason=prompt('Motivo de la anulación (opcional):','Irregularidades');if(reason===null)return;resolve(null,true,reason.trim()||'Anulación manual');});
function undo(){if(!previous)return;state=previous;previous=null;persist();render();}
$('undo').addEventListener('click',undo);$('result-undo').addEventListener('click',undo);
$('resume').addEventListener('click',()=>{const s=load(KEY);if(!isValid(s))return;state=s;previous=null;render();});
function setup(){ $('setup').hidden=false;$('play').hidden=true;$('results').hidden=true;$('score-section').hidden=true;$('resume-box').hidden=!isValid(load(KEY));$('resume').textContent=load(KEY)?.phase==='done'?'Ver resultados guardados':'Continuar partida';}
$('leave').addEventListener('click',()=>{persist();setup();});$('new-game').addEventListener('click',setup);
})();