'use strict';
(()=>{const $=id=>document.getElementById(id),C=window.TabooCore,KEY='aventura-prohibida-v2',SHARED='la-gran-aventura-v1';const defaults=['Exploradores','Valientes','Mensajeros','Guardianes','Soñadores','Pioneros','Viajeros','Sembradores'];let state=null,draft=defaults.slice(0,5),cooldown=0;
function load(k){try{return JSON.parse(localStorage.getItem(k));}catch(_){return null;}}
function store(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(_){$('storage-status').textContent='No se pudo guardar. Evita cerrar esta página durante la partida.';}}
function save(){store(KEY,state);}
function valid(s){return s?.version===2&&Array.isArray(s.teams)&&s.teams.length>=2&&s.teams.length<=8&&Array.isArray(s.decks)&&s.decks.length===s.teams.length&&s.decks.every(d=>Array.isArray(d)&&d.length>0&&d.every(c=>window.TABOO_BANK.some(b=>b.id===c.id)))&&Array.isArray(s.positions)&&s.positions.length===s.teams.length&&s.positions.every((p,i)=>Number.isInteger(p)&&p>=0&&p<=s.decks[i].length)&&Number.isInteger(s.turn)&&s.turn>=0&&Array.isArray(s.scores)&&s.scores.length===s.teams.length&&Array.isArray(s.history)&&['ready','playing','paused','ended','finished'].includes(s.phase)&&(!['playing','paused'].includes(s.phase)||s.active&&s.decks[C.team(s)].some(c=>c.id===s.active.id));}
const shared=load(SHARED);if(shared?.teams?.length>=2&&shared.teams.length<=8&&shared.teams.every(t=>typeof t.name==='string'))draft=shared.teams.map(t=>t.name);$('count').value=draft.length;
function read(){[...$('teams').querySelectorAll('input')].forEach((el,i)=>draft[i]=el.value.trim());}
function fields(){$('teams').replaceChildren();for(let i=0;i<Number($('count').value);i++){const l=document.createElement('label'),inp=document.createElement('input');l.textContent='Equipo '+(i+1);inp.required=true;inp.maxLength=50;inp.value=draft[i]??defaults[i];l.append(inp);$('teams').append(l);}}
$('count').addEventListener('change',()=>{read();fields();});fields();
function el(tag,text){const n=document.createElement(tag);n.textContent=text;return n;}
function setup(){$('setup').hidden=false;$('play').hidden=true;$('results').hidden=true;$('scores-section').hidden=true;$('resume-box').hidden=!valid(load(KEY));$('resume').textContent=load(KEY)?.phase==='finished'?'Ver resultados guardados':'Continuar partida';}
function clock(){if(!state)return;const now=Date.now();if(C.expire(state,now)){save();render();$('end').classList.add('expired');window.dispatchEvent(new CustomEvent('taboo-result',{detail:'timeout'}));}const ms=state.phase==='playing'?Math.max(0,state.deadline-now):state.phase==='paused'?state.remaining:state.phase==='ready'?90000:0;$('timer').textContent=Math.ceil(ms/1000)+' s';$('time-bar').value=ms/1000;for(const id of ['hit','pass'])$(id).disabled=state.phase!=='playing'||now<cooldown;}
function render(){const finished=state.phase==='finished';$('setup').hidden=true;$('play').hidden=finished;$('results').hidden=!finished;$('scores-section').hidden=false;$('ready').hidden=state.phase!=='ready';$('board').hidden=state.phase!=='playing';$('paused').hidden=state.phase!=='paused';$('end').hidden=state.phase!=='ended';$('round').textContent=`RONDA ${C.round(state)} · EQUIPO ${C.team(state)+1} DE ${state.teams.length}`;$('team').textContent=state.teams[C.team(state)];$('last').textContent=state.lastRound===C.round(state)?'⚑ Cerramos esta ronda ✓':'⚑ Última ronda';$('last').setAttribute('aria-pressed',String(state.lastRound===C.round(state)));$('last-info').hidden=state.lastRound===null;$('last-info').textContent=state.exhausted?'Un equipo agotó sus tarjetas. Los demás completarán esta ronda antes del resultado.':'Al terminar esta ronda, todos habrán tenido la misma cantidad de turnos.';$('feedback').textContent='';$('end').classList.remove('expired');
if(state.phase==='playing'){const card=C.current(state);$('category').textContent=`${card.type} · TARJETA ${state.shown} DEL TURNO`;$('target').textContent=card.title;}else{$('target').textContent='';}
if(state.phase==='ended'){const actions=state.history.filter(h=>h.turn===state.turn);$('end-title').textContent=state.exhausted&&state.positions[C.team(state)]===state.decks[C.team(state)].length?'¡Completaron sus tarjetas disponibles!':'¡Se acabó el tiempo!';$('turn-summary').textContent=`${actions.filter(h=>h.result==='hit').length} aciertos · ${actions.reduce((sum,h)=>sum+h.points,0)} puntos en este turno.`;const end=((state.turn+1)%state.teams.length===0&&state.lastRound===C.round(state));$('next').textContent=end?'Ver resultados →':'Preparar siguiente equipo →';}
$('scores').replaceChildren();state.teams.forEach((name,i)=>{const card=el('div','');card.append(el('strong',name),el('p',state.scores[i]+' puntos'));$('scores').append(card);});$('history').replaceChildren();state.history.slice().reverse().forEach(h=>$('history').append(el('li',`${state.teams[h.team]} · ${h.title} · ${{hit:'Acierto +10',pass:'Pase'}[h.result]}`)));
if(finished){const ranking=state.teams.map((name,i)=>({name,score:state.scores[i]})).sort((a,b)=>b.score-a.score);$('result-summary').textContent=`Cada equipo tuvo ${(state.turn+1)/state.teams.length} turnos. Primer lugar: ${ranking.filter(r=>r.score===ranking[0].score).map(r=>r.name).join(', ')}.`;$('podium').replaceChildren();ranking.forEach(r=>{const pos=ranking.findIndex(v=>v.score===r.score)+1,card=el('div','');card.append(el('strong',(pos<=3?['🥇','🥈','🥉'][pos-1]:pos+'.')+' '+r.name),el('p',r.score+' puntos'));$('podium').append(card);});}}
$('setup-form').addEventListener('submit',e=>{e.preventDefault();read();const names=draft.slice(0,Number($('count').value));if(names.some(n=>!n)||new Set(names.map(n=>n.toLocaleLowerCase('es'))).size!==names.length){$('error').textContent='Escribe un nombre diferente para cada equipo.';return;}const old=load(KEY);if(valid(old)&&old.phase!=='finished'&&!confirm('¿Reemplazar la partida guardada?'))return;state=C.create(names,window.TABOO_BANK);store(SHARED,{...(load(SHARED)||{}),teams:names.map(name=>({name,members:[]}))});save();render();clock();});
$('start').addEventListener('click',()=>{if(C.begin(state,Date.now())){cooldown=0;save();render();clock();}});
for(const [id,result]of [['hit','hit'],['pass','pass']])$(id).addEventListener('click',()=>{if(Date.now()<cooldown)return;if(C.answer(state,result,Date.now())){cooldown=Date.now()+700;save();render();$('feedback').textContent={hit:'¡Acierto! +10 puntos.',pass:'Tarjeta pasada: 0 puntos.'}[result];window.dispatchEvent(new CustomEvent('taboo-result',{detail:result}));}else{save();render();}clock();});
$('pause').addEventListener('click',()=>{C.pause(state,Date.now());save();render();clock();});$('unpause').addEventListener('click',()=>{if(C.resume(state,Date.now())){save();render();clock();}});$('last').addEventListener('click',()=>{C.markLast(state);save();render();clock();});$('next').addEventListener('click',()=>{if(C.next(state)){save();render();clock();$('team').scrollIntoView({block:'start'});}});$('leave').addEventListener('click',()=>{C.pause(state,Date.now());save();render();setup();});$('new-game').addEventListener('click',setup);$('resume').addEventListener('click',()=>{const saved=load(KEY);if(valid(saved)){state=saved;C.expire(state,Date.now());save();render();clock();}});document.addEventListener('visibilitychange',()=>{if(!document.hidden)clock();});window.addEventListener('pageshow',clock);setInterval(clock,100);setup();
})();
