'use strict';
(() => {
const params=new URLSearchParams(location.search),individual=params.get('modo')==='individual';
const $=id=>document.getElementById(id),bank=window.QUIZ_QUESTIONS,COUNT=20,KEY=individual?'aventura-quiz-individual-v5':'aventura-quiz-aula-v6',TEAMKEY='la-gran-aventura-v1';
const names=['Exploradores','Valientes','Mensajeros','Guardianes','Soñadores'];
let draft=names.map(name=>({name,members:[]})),session=null,timer=null,autoTimer=null,deadline=0,remaining=0,paused=false;
function readJSON(key){try{return JSON.parse(localStorage.getItem(key));}catch(_){return null;}}
const shared=readJSON(TEAMKEY);if(!individual&&shared&&Array.isArray(shared.teams)&&shared.teams.length>=2&&shared.teams.length<=5&&shared.teams.every(t=>typeof t.name==='string'&&Array.isArray(t.members)&&t.members.every(m=>typeof m==='string'))){draft=shared.teams;}
if(individual){document.querySelector('.topbar > span').textContent='QUIZ RELÁMPAGO · INDIVIDUAL';draft=[{name:'',members:[]}];const option=document.createElement('option');option.value='1';option.textContent='Un participante';$('team-count').replaceChildren(option);$('team-count').closest('label').hidden=true;$('individual-notice').hidden=false;document.querySelector('h1').textContent='Tu reto individual';document.querySelector('.intro').textContent='20 preguntas para poner a prueba lo que aprendiste. Lee con calma.';$('pace').innerHTML='<option value="30">30 segundos para todos</option>';$('pace').closest('label').hidden=true;document.body.classList.add('individual-mode');$('save-teams').hidden=true;$('pause').hidden=true;$('exit').hidden=true;document.querySelector('#setup-form h2').textContent='Prepara tu participación';document.querySelector('#setup-form h2 + p').textContent='Escribe tu nombre tal como quieres que aparezca en tu calificación.';}
$('team-count').value=draft.length;
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function takeDraft(){document.querySelectorAll('.quiz-team').forEach((el,i)=>{draft[i]={name:el.querySelector('input').value.trim(),members:[]};});}
function renderFields(){const count=Number($('team-count').value);$('team-fields').replaceChildren();for(let i=0;i<count;i++){const team=draft[i]||{name:names[i],members:[]};const wrap=document.createElement('div');wrap.className='quiz-team';const label=document.createElement('label');label.textContent=individual?'Tu nombre':'Nombre del equipo '+(i+1);const input=document.createElement('input');input.value=team.name;input.required=true;input.maxLength=60;input.autocomplete=individual?'name':'off';input.id='team-name-'+i;label.htmlFor=input.id;label.append(input);wrap.append(label);$('team-fields').append(wrap);}summary();}
function summary(){if(individual){$('setup-summary').textContent='20 preguntas · 30 segundos por pregunta · Un intento en este navegador. Misma combinación de niveles para todos.';return;}const n=Number($('team-count').value),sec=Number($('pace').value);$('setup-summary').textContent=(individual?'20 preguntas individuales. ':n+' equipos × 20 preguntas = '+n*20+' preguntas distintas. ')+ ' El tiempo de respuesta puede ocupar hasta '+Math.ceil(n*20*sec/60)+' minutos, más las explicaciones y los cambios de equipo.';}
function teamsFromForm(){takeDraft();const teams=draft.slice(0,Number($('team-count').value));if(teams.some(t=>!t.name)){throw Error('Escribe un nombre para cada equipo.');}if(new Set(teams.map(t=>t.name.toLocaleLowerCase('es'))).size!==teams.length)throw Error('Cada equipo necesita un nombre diferente.');return teams;}
function store(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch(_){$('storage-status').textContent='El navegador no pudo guardar los cambios. Puedes continuar, pero evita cerrar la página.';return false;}}
function saveTeams(teams){if(individual)return true;const previous=readJSON(TEAMKEY)||{};const changed=JSON.stringify(previous.teams)!==JSON.stringify(teams);return store(TEAMKEY,{teams,rounds:previous.rounds||5,games:changed?{}:previous.games||{}});}
function commitTeams(){try{const teams=teamsFromForm();$('setup-error').textContent='';if(saveTeams(teams))$('setup-status').textContent='Equipos guardados. También están disponibles en la portada.';}catch(e){$('setup-error').textContent=e.message;}}
$('save-teams').addEventListener('click',commitTeams);$('team-count').addEventListener('change',()=>{takeDraft();renderFields();});$('pace').addEventListener('change',summary);renderFields();
function stopTimers(){clearInterval(timer);clearTimeout(autoTimer);timer=null;autoTimer=null;}
function persist(){if(session)store(KEY,session);}
function valid(s){return s&&s.version===3&&Array.isArray(s.teams)&&s.teams.length>=(individual?1:2)&&s.teams.length<=5&&s.teams.every(t=>typeof t.name==='string'&&Array.isArray(t.members))&&Array.isArray(s.deck)&&s.deck.length===s.teams.length*COUNT&&s.deck.every(q=>q&&typeof q.question==='string'&&Array.isArray(q.options)&&q.options.length===4&&q.options.filter(o=>o.correct).length===1)&&Array.isArray(s.scores)&&s.scores.length===s.teams.length&&s.scores.every(Number.isFinite)&&Array.isArray(s.answers)&&Number.isInteger(s.index)&&s.index>=0&&s.index<=s.deck.length&&[25,30,40,45,60,90].includes(s.seconds)&&['ready','asking','feedback','done'].includes(s.phase);}
const config=null;
const LOCK='aventura-unico-individual-v1';
function isUsed(){const old=readJSON('aventura-intentos-v5');return Boolean(readJSON(LOCK)||readJSON(KEY)||(old&&Object.keys(old).length));}
function reserve(name){if(isUsed())throw Error('Este navegador ya tiene un intento individual. No se puede empezar otro, aunque cambies el nombre.');if(!store(LOCK,{name,startedAt:new Date().toISOString()}))throw Error('Necesitas permitir el almacenamiento local para registrar este único intento.');}
const saved=readJSON(KEY);$('resume-box').hidden=!valid(saved);if(valid(saved)&&saved.phase==='done')$('resume').textContent='Ver mi calificación guardada';if(individual&&isUsed()){$('setup-form').hidden=true;$('setup-error').textContent='';const msg=document.createElement('p');msg.className='notice';msg.textContent=valid(saved)?'Tu intento ya está registrado. Solo puedes continuarlo o consultar tu calificación.':'Este navegador ya registró un intento. No se puede iniciar otro con un nombre diferente.';$('resume-box').before(msg);}
// Each team receives at least two questions from each of the eight topics.
function buildDeck(count){const pools=Object.fromEntries(Object.entries(window.QUIZ_BANKS).map(([topic,questions])=>[topic,shuffle(questions.slice())]));const topics=shuffle(Object.keys(pools));const sets=Array.from({length:count},()=>[]);for(let t=0;t<count;t++){for(const topic of topics){const quota=topics.indexOf(topic)<2?4:3;const chosen=pools[topic].splice(0,quota);if(chosen.length!==quota)throw Error('No hay suficientes preguntas para todos los equipos.');sets[t].push(...chosen);}}return sets.flatMap(set=>shuffle(set).map(q=>({...q,options:shuffle(q.options.map((text,i)=>({text,correct:i===q.answer})))})));}
$('setup-form').addEventListener('submit',event=>{event.preventDefault();try{const teams=teamsFromForm();const currentSaved=readJSON(KEY);if(individual&&isUsed())throw Error('Ya hay un intento registrado en este navegador. Usa el botón para continuar o consultar tu resultado.');if(valid(currentSaved)&&currentSaved.phase!=='done'&&!confirm('Hay una partida guardada. ¿Reemplazarla por una nueva?'))return;const deck=buildDeck(teams.length);if(individual){if(valid(currentSaved)&&currentSaved.phase!=='done')throw Error('Termina el intento pendiente antes de empezar otro.');reserve(teams[0].name);}saveTeams(teams);stopTimers();session={version:3,teams,deck,index:0,scores:teams.map(()=>0),answers:[],seconds:individual?30:Number($('pace').value),advance:$('advance').value,phase:'ready',startedAt:new Date().toISOString()};persist();enter();ready();}catch(e){$('setup-error').textContent=e.message;}});
function enter(){paused=false;$('quiz-setup').hidden=true;$('results').hidden=true;$('quiz-play').hidden=false;$('score-section').hidden=false;$('pause-cover').hidden=true;$('pause').textContent='Pausar';score();}
function teamIndex(){return Math.min(session.teams.length-1,Math.floor(session.index/COUNT));}
function heading(){const t=session.teams[teamIndex()];$('round-label').textContent=(individual?'INDIVIDUAL':'EQUIPO '+(teamIndex()+1)+' DE '+session.teams.length)+' · PREGUNTA '+(session.index%COUNT+1)+' DE '+COUNT;$('turn').textContent=t.name;$('member').textContent=individual?'Responde por tu cuenta.':'Todo el equipo puede conversar y decidir.';}
function score(){const list=$('quiz-scoreboard');list.replaceChildren();session.teams.forEach((t,i)=>{const el=document.createElement('span');el.textContent=t.name+': '+session.scores[i]+' puntos';el.className=i===teamIndex()?'active-score':'';list.append(el);});}
function ready(){stopTimers();$('timeout-flash').hidden=true;paused=false;session.phase='ready';persist();heading();$('ready').hidden=false;$('question-area').hidden=true;$('pause-cover').hidden=true;$('pause').disabled=true;$('pause').textContent='Pausar';$('ready-title').textContent=(individual?'Tu turno, ':'Es el turno de ')+session.teams[teamIndex()].name;$('ready-text').textContent=individual?'Responde las 20 preguntas seguidas. No hay pausa ni vuelta atrás en esta demostración.':'Responderán 20 preguntas seguidas. Solo se detiene al cambiar de equipo.';$('timer').textContent=session.seconds;$('time-bar').max=session.seconds;$('time-bar').value=session.seconds;$('reveal').focus();score();}
function reveal(){stopTimers();paused=false;session.phase='asking';session.deadline=Date.now()+session.seconds*1000;deadline=session.deadline;remaining=session.seconds*1000;persist();renderQuestion();timer=setInterval(tick,80);tick();}
function renderQuestion(){heading();$('ready').hidden=true;$('question-area').hidden=false;$('correction').hidden=true;$('pause-cover').hidden=true;$('next').hidden=true;$('auto-status').textContent='';$('pause').disabled=false;$('pause').textContent='Pausar';$('topic').textContent=session.deck[session.index].topic+' · '+session.deck[session.index].difficulty;$('question').textContent=session.deck[session.index].question;$('options').replaceChildren();session.deck[session.index].options.forEach((o,i)=>{const b=document.createElement('button');b.textContent=String.fromCharCode(65+i)+'. '+o.text;b.addEventListener('click',()=>{if(paused||session.phase!=='asking')return;if(Date.now()>=deadline){finish(null);return;}finish(i);});$('options').append(b);});$('options').firstElementChild.focus();}
function tick(){if(paused||session.phase!=='asking')return;remaining=Math.max(0,deadline-Date.now());$('timer').textContent=Math.ceil(remaining/1000);$('time-bar').max=session.seconds;$('time-bar').value=remaining/1000;if(!remaining)finish(null);}
function finish(choice){if(session.phase!=='asking')return;stopTimers();const q=session.deck[session.index],correct=choice!==null&&q.options[choice].correct;session.scores[teamIndex()]+=correct?100:0;session.answers.push({team:teamIndex(),questionId:q.id,question:q.question,topic:q.topic,chosen:choice===null?'Sin respuesta':q.options[choice].text,correctAnswer:q.options.find(o=>o.correct).text,correct,points:correct?100:0,reference:q.reference});session.phase='feedback';delete session.pausedRemaining;persist();feedback();}
function feedback(){const a=session.answers[session.answers.length-1];paused=false;$('ready').hidden=true;$('question-area').hidden=false;$('pause-cover').hidden=true;$('correction').hidden=true;$('next').hidden=true;$('pause').disabled=true;[...$('options').children].forEach(b=>b.disabled=true);score();
const kind=a.chosen==='Sin respuesta'?'timeout':a.correct?'correct':'wrong';const overlay=$('timeout-flash');overlay.className='timeout-flash '+kind;overlay.querySelector('span').textContent=kind==='correct'?'✓':kind==='wrong'?'✕':'⌛';overlay.querySelector('strong').textContent=kind==='correct'?'¡Bien hecho! +100':kind==='wrong'?'¡Sigue intentándolo!':'¡Se acabó el tiempo!';overlay.querySelector('p').textContent='Vamos con la siguiente pregunta…';overlay.hidden=false;window.dispatchEvent(new CustomEvent('quiz-feedback',{detail:kind}));autoTimer=setTimeout(()=>{overlay.hidden=true;next();},1100);}
function next(){if(session.phase!=='feedback'||paused)return;stopTimers();session.index++;if(session.index===session.deck.length){session.phase='done';persist();results();}else if(session.index%COUNT===0){ready();}else reveal();}
$('reveal').addEventListener('click',reveal);$('next').addEventListener('click',next);
$('pause').addEventListener('click',()=>{if(session.phase==='ready')return;if(!paused&&session.phase==='asking'&&Date.now()>=deadline){finish(null);return;}paused=!paused;if(paused){remaining=Math.max(0,deadline-Date.now());stopTimers();if(session.phase==='asking'){session.pausedRemaining=remaining;persist();}$('question-area').hidden=true;$('pause-cover').hidden=false;$('pause').textContent='Continuar';}else{$('pause-cover').hidden=true;$('question-area').hidden=false;$('pause').textContent='Pausar';if(session.phase==='asking'){deadline=Date.now()+remaining;session.deadline=deadline;delete session.pausedRemaining;persist();timer=setInterval(tick,80);tick();}else feedback();}});
$('exit').addEventListener('click',()=>{if(!confirm('¿Volver a preparación? La partida quedará guardada.'))return;if(session.phase==='asking'){remaining=paused?remaining:Math.max(0,deadline-Date.now());session.pausedRemaining=remaining;}stopTimers();persist();$('quiz-play').hidden=true;$('quiz-setup').hidden=false;$('score-section').hidden=true;$('resume-box').hidden=false;});
$('resume').addEventListener('click',()=>{const s=readJSON(KEY);if(!valid(s)){alert('No se pudo recuperar la partida. Prepara una nueva.');return;}session=s;enter();if(s.phase==='ready')ready();else if(s.phase==='done')results();else if(s.phase==='feedback'){renderQuestion();feedback();}else{renderQuestion();if(typeof s.pausedRemaining==='number'){remaining=s.pausedRemaining;paused=true;$('pause-cover').hidden=false;$('question-area').hidden=true;$('pause').textContent='Continuar';}else{deadline=s.deadline;timer=setInterval(tick,80);tick();}}});
function ranking(){return session.teams.map((t,i)=>({name:t.name,score:session.scores[i],correct:session.answers.filter(a=>a.team===i&&a.correct).length})).sort((a,b)=>b.score-a.score);}
function results(){stopTimers();$('result-image').hidden=!individual;$('again').hidden=individual;$('quiz-play').hidden=true;$('quiz-setup').hidden=true;$('results').hidden=false;$('score-section').hidden=true;const rows=ranking(),winners=rows.filter(r=>r.score===rows[0].score);$('winner').textContent=individual?'Tu calificación: '+session.scores[0]+' / 2.000 puntos · '+(session.scores[0]/200).toFixed(1)+' / 10.':(winners.length>1?'Primer lugar compartido: ':'Equipo ganador: ')+winners.map(r=>r.name).join(', ')+'.';$('podium').replaceChildren();$('result-rows').replaceChildren();rows.forEach(r=>{const position=rows.findIndex(x=>x.score===r.score)+1;if(position<=3){const card=document.createElement('div');card.className='podium-card';const title=document.createElement('strong');title.textContent=['🥇','🥈','🥉'][position-1]+' '+r.name;const pts=document.createElement('p');pts.textContent=r.score+' puntos';card.append(title,pts);$('podium').append(card);}const tr=document.createElement('tr');[position,r.name,r.correct+'/20',r.score].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});$('result-rows').append(tr);});$('answer-review').replaceChildren();session.answers.forEach(a=>{const el=document.createElement('p');el.textContent=session.teams[a.team].name+' · '+a.question+' — Eligieron: '+a.chosen+'. Correcta: '+a.correctAnswer+' ('+a.reference+'). '+a.points+' puntos.';$('answer-review').append(el);});}
$('again').addEventListener('click',()=>{$('results').hidden=true;$('quiz-setup').hidden=false;$('resume-box').hidden=true;});
function csvCell(value){let s=String(value);if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
$('download').addEventListener('click',()=>{const rows=[['Equipo','Pregunta','Respuesta elegida','Respuesta correcta','Puntos','Referencia'],...session.answers.map(a=>[session.teams[a.team].name,a.question,a.chosen,a.correctAnswer,a.points,a.reference])];const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='quiz-resultados.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
window.addEventListener('pagehide',stopTimers);window.addEventListener('pageshow',e=>{if(e.persisted&&session?.phase==='asking'&&!paused){timer=setInterval(tick,80);tick();}});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&session?.phase==='asking'&&!paused)tick();});

$('result-image').addEventListener('click',()=>{if(!session||session.phase!=='done')return;const c=document.createElement('canvas');c.width=1200;c.height=900;const x=c.getContext('2d');x.fillStyle='#f0e9ff';x.fillRect(0,0,1200,900);x.fillStyle='#742bda';x.fillRect(0,0,1200,175);x.fillStyle='white';x.textAlign='center';x.font='bold 48px Arial';x.fillText('LA GRAN AVENTURA',600,80);x.font='26px Arial';x.fillText('Quiz Relámpago · Calificación individual',600,130);x.fillStyle='#382451';x.font='bold 44px Arial';const name=session.teams[0].name;let size=44;while(x.measureText(name).width>1080&&size>16){x.font='bold '+(--size)+'px Arial';}x.fillText(name,600,265);x.fillStyle='#742bda';x.font='bold 105px Arial';x.fillText((session.scores[0]/200).toFixed(1)+' / 10',600,410);x.fillStyle='#382451';x.font='32px Arial';x.fillText(session.scores[0]+' / 2.000 puntos',600,480);x.fillText(session.answers.filter(a=>a.correct).length+' aciertos de 20 preguntas',600,545);x.font='24px Arial';x.fillText('Tiempo por pregunta: '+session.seconds+' segundos',600,615);x.fillText('Inicio: '+new Date(session.startedAt).toLocaleString('es'),600,665);x.font='20px Arial';x.fillText('Resultado local · No verificado por un servidor',600,785);x.fillText('Comparte esta imagen con quien dirige tu clase.',600,825);c.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mi-calificacion-quiz.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);},'image/png');});
})();
