'use strict';
(()=>{
const $=id=>document.getElementById(id),C=window.WordleCore,KEY='aventura-wordle-v2',SHARED='la-gran-aventura-v1';
const defaults=['Exploradores','Valientes','Mensajeros','Guardianes','Soñadores','Pioneros','Viajeros','Sembradores'];let state=null,draft=defaults.slice(0,5);
function load(k){try{return JSON.parse(localStorage.getItem(k));}catch(_){return null;}}
function store(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(_){$('storage-status').textContent='No se pudo guardar. Evita cerrar esta página durante la partida.';}}
function save(){store(KEY,state);}
function valid(s){return s?.version===1&&Array.isArray(s.teams)&&s.teams.length>=2&&s.teams.length<=8&&s.teams.every(t=>typeof t==='string')&&Array.isArray(s.deck)&&s.deck.length>=s.teams.length&&s.deck.every(w=>window.WORDLE_BANK.some(b=>b.word===w.word))&&Number.isInteger(s.turn)&&s.turn>=0&&s.turn<s.deck.length&&Array.isArray(s.guesses)&&s.guesses.length<=6&&Array.isArray(s.scores)&&s.scores.length===s.teams.length&&Array.isArray(s.history)&&typeof s.input==='string'&&['ready','playing','won','lost','finished'].includes(s.phase);}
const shared=load(SHARED);if(shared?.teams?.length>=2&&shared.teams.length<=8&&shared.teams.every(t=>typeof t.name==='string'))draft=shared.teams.map(t=>t.name);
$('count').value=draft.length;
function readNames(){[...$('teams').querySelectorAll('input')].forEach((el,i)=>draft[i]=el.value.trim());}
function fields(){$('teams').replaceChildren();for(let i=0;i<Number($('count').value);i++){const l=document.createElement('label'),inp=document.createElement('input');l.textContent='Equipo '+(i+1);inp.required=true;inp.maxLength=50;inp.value=draft[i]??defaults[i];l.append(inp);$('teams').append(l);}}
$('count').addEventListener('change',()=>{readNames();fields();});fields();
function setup(){$('setup').hidden=false;$('play').hidden=true;$('results').hidden=true;$('scores-section').hidden=true;$('resume-box').hidden=!valid(load(KEY));$('resume').textContent=load(KEY)?.phase==='finished'?'Ver resultados guardados':'Continuar partida';}
function element(tag,text,className){const el=document.createElement(tag);el.textContent=text;if(className)el.className=className;return el;}
function current(){return state.deck[state.turn];}
function message(text){$('feedback').textContent=text;}
function drawGrid(reveal=false){const length=C.normalize(current().word).length;$('grid').style.setProperty('--letters',length);$('grid').replaceChildren();for(let r=0;r<6;r++){const past=state.guesses[r];const input=past?.word??(r===state.guesses.length?state.input:'');for(let col=0;col<length;col++){const color=past?.colors[col],symbol=color?{correct:'✓',present:'↔',absent:'×'}[color]:'';const tile=element('div',input[col]??'','letter'+(color?' '+color:r===state.guesses.length&&state.phase==='playing'?' current':''));tile.setAttribute('aria-label',`Intento ${r+1}, posición ${col+1}: ${input[col]??'vacía'}${color?', '+{correct:'correcta',present:'en otra posición',absent:'sin otra coincidencia'}[color]:''}`);if(symbol){const mark=element('small',symbol);mark.setAttribute('aria-hidden','true');tile.append(mark);}if(reveal&&r===state.guesses.length-1){tile.classList.add('reveal');tile.style.animationDelay=col*60+'ms';}$('grid').append(tile);}}
const strength={absent:1,present:2,correct:3},known={};state.guesses.forEach(g=>[...g.word].forEach((c,i)=>{if((strength[g.colors[i]]??0)>(strength[known[c]]??0))known[c]=g.colors[i];}));$('keyboard').replaceChildren();for(const row of ['QWERTYUIOP','ASDFGHJKLÑ','ZXCVBNM']){const div=element('div','','key-row');const keys=[...row];if(row==='ZXCVBNM')keys.unshift('ENTER');if(row==='ZXCVBNM')keys.push('BACKSPACE');keys.forEach(key=>{const label=key==='ENTER'?'Probar':key==='BACKSPACE'?'⌫':key,b=element('button',label,'key'+(key.length>1?' wide':'')+(known[key]?' '+known[key]:''));b.type='button';b.disabled=state.phase!=='playing';b.setAttribute('aria-label',key==='BACKSPACE'?'Borrar última letra':key==='ENTER'?'Comprobar palabra':key+(known[key]?', '+{correct:'posición confirmada',present:'presente',absent:'sin coincidencia'}[known[key]]:''));b.addEventListener('click',()=>keyInput(key));div.append(b);});$('keyboard').append(div);}}
function render(reveal=false){const done=state.phase==='finished',resolved=['won','lost'].includes(state.phase);$('setup').hidden=true;$('play').hidden=done;$('results').hidden=!done;$('scores-section').hidden=false;$('round').textContent=`RONDA ${C.round(state)} · EQUIPO ${C.team(state)+1} DE ${state.teams.length}`;$('team').textContent=state.teams[C.team(state)];$('last').setAttribute('aria-pressed',String(state.lastRound===C.round(state)));$('last').textContent=state.lastRound===C.round(state)?'⚑ Cerramos esta ronda ✓':'⚑ Última ronda';$('last-info').hidden=state.lastRound===null;$('last-info').textContent='Terminaremos al completar esta ronda. Los equipos que faltan conservan su turno.';$('ready').hidden=state.phase!=='ready';$('board').hidden=state.phase==='ready'||done;$('solution').hidden=!resolved;$('category').textContent=current().type+' · '+C.normalize(current().word).length+' letras';$('attempts').textContent=state.guesses.length+' de 6 intentos';$('hint').hidden=!state.hint;$('hint').textContent=current().hint;$('hint-button').disabled=state.hint||state.phase!=='playing';$('hint-button').textContent=state.hint?'Pista descubierta':'Una pequeña pista 💡';drawGrid(reveal);message('');
if(resolved){$('solution').classList.toggle('won',state.phase==='won');const last=state.history.at(-1);$('solution-title').textContent=state.phase==='won'?`¡Lo descubrieron! +${last.points} puntos`:'Seis intentos, una palabra para recordar';$('solution-text').textContent=current().word;$('solution-reference').textContent='Referencia: '+current().reference;const ending=state.turn+1===state.deck.length||((state.turn+1)%state.teams.length===0&&state.lastRound===C.round(state));$('next').textContent=ending?'Ver resultados →':'Preparar al siguiente equipo →';}
$('scores').replaceChildren();state.teams.forEach((name,i)=>{const card=element('div','');card.append(element('strong',name),element('p',`${state.scores[i]} puntos · ${state.history.filter(h=>h.team===i).length} turnos`));$('scores').append(card);});$('history').replaceChildren();state.history.slice().reverse().forEach(h=>$('history').append(element('li',`${state.teams[h.team]} · ${h.word} · ${h.points} puntos · ${h.attempts} intentos`)));
if(done){const ranking=state.teams.map((name,i)=>({name,score:state.scores[i]})).sort((a,b)=>b.score-a.score);$('result-summary').textContent=`Cada equipo jugó ${state.history.length/state.teams.length} palabras. Primer lugar: ${ranking.filter(r=>r.score===ranking[0].score).map(r=>r.name).join(', ')}.`;$('podium').replaceChildren();ranking.forEach(r=>{const pos=ranking.findIndex(v=>v.score===r.score)+1,card=element('div','');card.append(element('strong',(pos<=3?['🥇','🥈','🥉'][pos-1]:pos+'.')+' '+r.name),element('p',r.score+' puntos'));$('podium').append(card);});}}
function keyInput(key){if(!state||state.phase!=='playing'||$('play').hidden)return;if(key==='ENTER'){const result=C.submit(state,state.input);if(result==='length'||result==='duplicate'){message(result==='length'?'Completen las '+C.normalize(current().word).length+' letras antes de probar.':'Ya probaron esa palabra. Elijan otra; no se gastó un intento.');$('grid').classList.remove('shake');void $('grid').offsetWidth;$('grid').classList.add('shake');return;}save();render(true);if(result==='playing')message('Revisen los colores y conversen sobre el siguiente intento.');window.dispatchEvent(new CustomEvent('wordle-result',{detail:result}));}else{if(key==='BACKSPACE')state.input=state.input.slice(0,-1);else{key=C.normalize(key);if(!/^[A-ZÑ]$/.test(key)||state.input.length>=C.normalize(current().word).length)return;state.input+=key;}save();drawGrid();message('');}}
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.altKey||e.metaKey||e.isComposing||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(!state||state.phase!=='playing'||$('play').hidden)return;const k=e.key==='Enter'?'ENTER':e.key==='Backspace'?'BACKSPACE':e.key;if(k==='ENTER'&&e.target.tagName==='BUTTON')return;if(k==='ENTER'||k==='BACKSPACE'||/^[a-záéíóúüñ]$/i.test(k)){e.preventDefault();keyInput(k);}});
$('setup-form').addEventListener('submit',e=>{e.preventDefault();readNames();const names=draft.slice(0,Number($('count').value));if(names.some(n=>!n)||new Set(names.map(n=>n.toLocaleLowerCase('es'))).size!==names.length){$('error').textContent='Escribe un nombre diferente para cada equipo.';return;}const old=load(KEY);if(valid(old)&&old.phase!=='finished'&&!confirm('¿Reemplazar la partida guardada?'))return;state=C.create(names,window.WORDLE_BANK);store(SHARED,{...(load(SHARED)||{}),teams:names.map(name=>({name,members:[]}))});save();render();});
$('start').addEventListener('click',()=>{if(C.begin(state)){save();render();}});$('hint-button').addEventListener('click',()=>{if(state.phase!=='playing')return;state.hint=true;save();render();});$('last').addEventListener('click',()=>{C.markLast(state);save();render();});$('next').addEventListener('click',()=>{if(C.next(state)){save();render();$('team').scrollIntoView({block:'start'});}});$('resume').addEventListener('click',()=>{const saved=load(KEY);if(valid(saved)){state=saved;render();}});$('leave').addEventListener('click',()=>{save();setup();});$('new-game').addEventListener('click',setup);setup();
})();
